[workspace]
members = [
]
[package]
name = "doggercom"
authors = ["e792a8"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "c2rust_out"
path = "c2rust-lib.rs"
crate-type = ["staticlib", "rlib"]
[[bin]]
path = "main.rs"
name = "main"
[dependencies]
libc= "0.2"
